## This is a RESTFUL and template implemntation of a Renesola MRG read 
# THANK GOD that the server supports http range headers, which means  that you don't have to fetch
# the entire file, which is good, because it gets longer and longer every minute, literally
# and anotehr weird, nice thing is that this is a rare use case for the NEGATIVE range header which
# only reads back the LAST x bytes of the file, and in our case, the Renesola MRG just appends data to the
# same file, so the latest data is always at the end. 

# So here's the gist of what's going on in this Jinja2 template - We fetch the relevant min.dat, but only the last 100 bytes
# and then split it the first time to just contain the last line with the /n char. From there, we split it a second time by spaces
# because the file is space delimited, in to 9 floating point numbers that go in to sensors like a normal REST sensor.
# Select your inverter module by changing the folder - /data/X/min.dat where 0 for X is the system total, and 1,2,3 etc are the
# various inverters that you set up on the MRG's actual interface

# Now I'll admit I could have done this a bit more..clean maybe. There's probably a neat way to increment the sensor
# names and whatever, but I'm not an expert in this stuff, so I just made a BIG template.

sensor:
  - platform: rest
    name: Renesola MRG
    scan_interval: 60
    # Obviously chage the IP to whatever your local IP is for your MRG. Suggest you make yours static and give it a bad gateway
    # to keep it from talking to any creepy Chinese servers or engaging in other tomfoolery. 
    resource: http://10.44.63.28/data/0/min.dat
    headers:
      range: bytes=-100
    value_template: "{{ value }}"

  # Change that folder from 0 to 1 or whatever to start looking at individual modules 
  # also, change your names and sensor names. This will be tiring in big installations. 
  - platform: rest
    name: Renesola Module 1
    scan_interval: 60
    resource: http://10.44.63.28/data/1/min.dat
    headers:
      range: bytes=-100
    value_template: "{{ value }}"

  # And increment everything again for the next inverter
  - platform: rest
    name: Renesola Module 2
    scan_interval: 60
    resource: http://10.44.63.28/data/2/min.dat
    headers:
      range: bytes=-100
    value_template: "{{ value }}"

  # And increment everything again for the next inverter
  - platform: rest
    name: Renesola Module 3
    scan_interval: 60
    resource: http://10.44.63.28/data/3/min.dat
    headers:
      range: bytes=-100
    value_template: "{{ value }}"

  # And increment everything again for the next inverter
  - platform: rest
    name: Renesola Module 4
    scan_interval: 60
    resource: http://10.44.63.28/data/4/min.dat
    headers:
      range: bytes=-100
    value_template: "{{ value }}"

  # And increment everything again for the next inverter
  - platform: rest
    name: Renesola Module 5
    scan_interval: 60
    resource: http://10.44.63.28/data/5/min.dat
    headers:
      range: bytes=-100
    value_template: "{{ value }}"

  # And increment everything again for the next inverter
  - platform: rest
    name: Renesola Module 6
    scan_interval: 60
    resource: http://10.44.63.28/data/6/min.dat
    headers:
      range: bytes=-100
    value_template: "{{ value }}"

  # Let's do a sensor for total energy
  - platform: rest
    name: Renesola MRG Lifetime
    scan_interval: 60
    resource: http://10.44.63.28/total/energy
    headers:
      range: bytes=0-13
    value_template: "{{ value }}"

template:
  - sensor:
      # No need to log the date and time - Homeassistant does this. It will just grind your disk. 
      # renesola_date, renesola_time etc. are left commented out from the original config.

      # System total, from Renesola MRG
      - name: "Solar Total kWh Today"
        default_entity_id: sensor.renesola_total_energy
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.renesola_mrg').split('\\n')[1].split(' ')[8] | float }}"

      # Module 1
      - name: "Solar Kilowatts"
        default_entity_id: sensor.module_1_renesola_power
        device_class: power
        unit_of_measurement: "kW"
        state: "{{ states('sensor.renesola_module_1').split('\\n')[1].split(' ')[2] | float }}"
      - name: "DC Panel Voltage"
        default_entity_id: sensor.module_1_renesola_vdc
        device_class: voltage
        unit_of_measurement: "V"
        state: "{{ states('sensor.renesola_module_1').split('\\n')[1].split(' ')[3] | float }}"
      - name: "AC Line Voltage"
        default_entity_id: sensor.module_1_renesola_vac
        device_class: voltage
        unit_of_measurement: "V"
        state: "{{ states('sensor.renesola_module_1').split('\\n')[1].split(' ')[4] | float }}"
      - name: "AC Output Amps"
        default_entity_id: sensor.module_1_renesola_ac_current
        device_class: current
        unit_of_measurement: "A"
        state: "{{ states('sensor.renesola_module_1').split('\\n')[1].split(' ')[5] | float }}"
      - name: "AC Frequency"
        default_entity_id: sensor.module_1_renesola_hz
        device_class: frequency
        unit_of_measurement: "Hz"
        state: "{{ states('sensor.renesola_module_1').split('\\n')[1].split(' ')[6] | float }}"
      - name: "Inverter Temperature"
        default_entity_id: sensor.module_1_renesola_module_temp
        device_class: temperature
        unit_of_measurement: "°C"
        state: >-
          {% set magic = states('sensor.renesola_module_1').split('\n')[1].split(' ')[7] %}
          {% if magic | float > -50 %}
            {{ magic }}
          {% else %}
            {{ 'unavailable' }}
          {% endif %}
      - name: "Solar Total kWh Today"
        default_entity_id: sensor.module_1_renesola_total_energy
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.renesola_module_1').split('\\n')[1].split(' ')[8] | float }}"

      # Module 2
      - name: "Solar Kilowatts"
        default_entity_id: sensor.module_2_renesola_power
        device_class: power
        unit_of_measurement: "kW"
        state: "{{ states('sensor.renesola_module_2').split('\\n')[1].split(' ')[2] | float }}"
      - name: "DC Panel Voltage"
        default_entity_id: sensor.module_2_renesola_vdc
        device_class: voltage
        unit_of_measurement: "V"
        state: "{{ states('sensor.renesola_module_2').split('\\n')[1].split(' ')[3] | float }}"
      - name: "AC Line Voltage"
        default_entity_id: sensor.module_2_renesola_vac
        device_class: voltage
        unit_of_measurement: "V"
        state: "{{ states('sensor.renesola_module_2').split('\\n')[1].split(' ')[4] | float }}"
      - name: "AC Output Amps"
        default_entity_id: sensor.module_2_renesola_ac_current
        device_class: current
        unit_of_measurement: "A"
        state: "{{ states('sensor.renesola_module_2').split('\\n')[1].split(' ')[5] | float }}"
      - name: "AC Frequency"
        default_entity_id: sensor.module_2_renesola_hz
        device_class: frequency
        unit_of_measurement: "Hz"
        state: "{{ states('sensor.renesola_module_2').split('\\n')[1].split(' ')[6] | float }}"
      - name: "Inverter Temperature"
        default_entity_id: sensor.module_2_renesola_module_temp
        device_class: temperature
        unit_of_measurement: "°C"
        state: >-
          {% set magic = states('sensor.renesola_module_2').split('\n')[1].split(' ')[7] %}
          {% if magic | float > -50 %}
            {{ magic }}
          {% else %}
            {{ 'unavailable' }}
          {% endif %}
      - name: "Solar Total kWh Today"
        default_entity_id: sensor.module_2_renesola_total_energy
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.renesola_module_2').split('\\n')[1].split(' ')[8] | float }}"

      # Module 3
      - name: "Solar Kilowatts"
        default_entity_id: sensor.module_3_renesola_power
        device_class: power
        unit_of_measurement: "kW"
        state: "{{ states('sensor.renesola_module_3').split('\\n')[1].split(' ')[2] | float }}"
      - name: "DC Panel Voltage"
        default_entity_id: sensor.module_3_renesola_vdc
        device_class: voltage
        unit_of_measurement: "V"
        state: "{{ states('sensor.renesola_module_3').split('\\n')[1].split(' ')[3] | float }}"
      - name: "AC Line Voltage"
        default_entity_id: sensor.module_3_renesola_vac
        device_class: voltage
        unit_of_measurement: "V"
        state: "{{ states('sensor.renesola_module_3').split('\\n')[1].split(' ')[4] | float }}"
      - name: "AC Output Amps"
        default_entity_id: sensor.module_3_renesola_ac_current
        device_class: current
        unit_of_measurement: "A"
        state: "{{ states('sensor.renesola_module_3').split('\\n')[1].split(' ')[5] | float }}"
      - name: "AC Frequency"
        default_entity_id: sensor.module_3_renesola_hz
        device_class: frequency
        unit_of_measurement: "Hz"
        state: "{{ states('sensor.renesola_module_3').split('\\n')[1].split(' ')[6] | float }}"
      - name: "Inverter Temperature"
        default_entity_id: sensor.module_3_renesola_module_temp
        device_class: temperature
        unit_of_measurement: "°C"
        state: >-
          {% set magic = states('sensor.renesola_module_3').split('\n')[1].split(' ')[7] %}
          {% if magic | float > -50 %}
            {{ magic }}
          {% else %}
            {{ 'unavailable' }}
          {% endif %}
      - name: "Solar Total kWh Today"
        default_entity_id: sensor.module_3_renesola_total_energy
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.renesola_module_3').split('\\n')[1].split(' ')[8] | float }}"

      # Module 4
      - name: "Solar Kilowatts"
        default_entity_id: sensor.module_4_renesola_power
        device_class: power
        unit_of_measurement: "kW"
        state: "{{ states('sensor.renesola_module_4').split('\\n')[1].split(' ')[2] | float }}"
      - name: "DC Panel Voltage"
        default_entity_id: sensor.module_4_renesola_vdc
        device_class: voltage
        unit_of_measurement: "V"
        state: "{{ states('sensor.renesola_module_4').split('\\n')[1].split(' ')[3] | float }}"
      - name: "AC Line Voltage"
        default_entity_id: sensor.module_4_renesola_vac
        device_class: voltage
        unit_of_measurement: "V"
        state: "{{ states('sensor.renesola_module_4').split('\\n')[1].split(' ')[4] | float }}"
      - name: "AC Output Amps"
        default_entity_id: sensor.module_4_renesola_ac_current
        device_class: current
        unit_of_measurement: "A"
        state: "{{ states('sensor.renesola_module_4').split('\\n')[1].split(' ')[5] | float }}"
      - name: "AC Frequency"
        default_entity_id: sensor.module_4_renesola_hz
        device_class: frequency
        unit_of_measurement: "Hz"
        state: "{{ states('sensor.renesola_module_4').split('\\n')[1].split(' ')[6] | float }}"
      - name: "Inverter Temperature"
        default_entity_id: sensor.module_4_renesola_module_temp
        device_class: temperature
        unit_of_measurement: "°C"
        state: >-
          {% set magic = states('sensor.renesola_module_4').split('\n')[1].split(' ')[7] %}
          {% if magic | float > -50 %}
            {{ magic }}
          {% else %}
            {{ 'unavailable' }}
          {% endif %}
      - name: "Solar Total kWh Today"
        default_entity_id: sensor.module_4_renesola_total_energy
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.renesola_module_4').split('\\n')[1].split(' ')[8] | float }}"

      # Module 5
      - name: "Solar Kilowatts"
        default_entity_id: sensor.module_5_renesola_power
        device_class: power
        unit_of_measurement: "kW"
        state: "{{ states('sensor.renesola_module_5').split('\\n')[1].split(' ')[2] | float }}"
      - name: "DC Panel Voltage"
        default_entity_id: sensor.module_5_renesola_vdc
        device_class: voltage
        unit_of_measurement: "V"
        state: "{{ states('sensor.renesola_module_5').split('\\n')[1].split(' ')[3] | float }}"
      - name: "AC Line Voltage"
        default_entity_id: sensor.module_5_renesola_vac
        device_class: voltage
        unit_of_measurement: "V"
        state: "{{ states('sensor.renesola_module_5').split('\\n')[1].split(' ')[4] | float }}"
      - name: "AC Output Amps"
        default_entity_id: sensor.module_5_renesola_ac_current
        device_class: current
        unit_of_measurement: "A"
        state: "{{ states('sensor.renesola_module_5').split('\\n')[1].split(' ')[5] | float }}"
      - name: "AC Frequency"
        default_entity_id: sensor.module_5_renesola_hz
        device_class: frequency
        unit_of_measurement: "Hz"
        state: "{{ states('sensor.renesola_module_5').split('\\n')[1].split(' ')[6] | float }}"
      - name: "Inverter Temperature"
        default_entity_id: sensor.module_5_renesola_module_temp
        device_class: temperature
        unit_of_measurement: "°C"
        state: >-
          {% set magic = states('sensor.renesola_module_5').split('\n')[1].split(' ')[7] %}
          {% if magic | float > -50 %}
            {{ magic }}
          {% else %}
            {{ 'unavailable' }}
          {% endif %}
      - name: "Solar Total kWh Today"
        default_entity_id: sensor.module_5_renesola_total_energy
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.renesola_module_5').split('\\n')[1].split(' ')[8] | float }}"

      # Module 6
      - name: "Solar Kilowatts"
        default_entity_id: sensor.module_6_renesola_power
        device_class: power
        unit_of_measurement: "kW"
        state: "{{ states('sensor.renesola_module_6').split('\\n')[1].split(' ')[2] | float }}"
      - name: "DC Panel Voltage"
        default_entity_id: sensor.module_6_renesola_vdc
        device_class: voltage
        unit_of_measurement: "V"
        state: "{{ states('sensor.renesola_module_6').split('\\n')[1].split(' ')[3] | float }}"
      - name: "AC Line Voltage"
        default_entity_id: sensor.module_6_renesola_vac
        device_class: voltage
        unit_of_measurement: "V"
        state: "{{ states('sensor.renesola_module_6').split('\\n')[1].split(' ')[4] | float }}"
      - name: "AC Output Amps"
        default_entity_id: sensor.module_6_renesola_ac_current
        device_class: current
        unit_of_measurement: "A"
        state: "{{ states('sensor.renesola_module_6').split('\\n')[1].split(' ')[5] | float }}"
      - name: "AC Frequency"
        default_entity_id: sensor.module_6_renesola_hz
        device_class: frequency
        unit_of_measurement: "Hz"
        state: "{{ states('sensor.renesola_module_6').split('\\n')[1].split(' ')[6] | float }}"
      - name: "Inverter Temperature"
        default_entity_id: sensor.module_6_renesola_module_temp
        device_class: temperature
        unit_of_measurement: "°C"
        state: >-
          {% set magic = states('sensor.renesola_module_6').split('\n')[1].split(' ')[7] %}
          {% if magic | float > -50 %}
            {{ magic }}
          {% else %}
            {{ 'unavailable' }}
          {% endif %}
      - name: "Solar Total kWh Today"
        default_entity_id: sensor.module_6_renesola_total_energy
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.renesola_module_6').split('\\n')[1].split(' ')[8] | float }}"

      # Lifetime money (from Renesola MRG Lifetime)
      - name: "Lifetime Array Payback"
        default_entity_id: sensor.renesola_combined_lifetime_money
        unit_of_measurement: "$"
        state: "{{ (states('sensor.renesola_mrg_lifetime').split('\\n')[0].split(' ')[0] | float * 0.00023) | round(2, common) }}"
